export const EDIT_USER_PROFILE_REQUEST = "EDIT_USER_PROFILE_REQUEST";
export const EDIT_USER_PROFILE_SUCCESS = "EDIT_USER_PROFILE_SUCCESS";
export const EDIT_USER_PROFILE_FAILURE = "EDIT_USER_PROFILE_FAILURE";
export const GET_AUTHENTICATED_USER_REQUEST = "GET_AUTHENTICATED_USER_REQUEST";
export const GET_AUTHENTICATED_USER_SUCCESS = "GET_AUTHENTICATED_USER_SUCCESS";
export const GET_AUTHENTICATED_USER_FAILURE = "GET_AUTHENTICATED_USER_FAILURE";
